export const notificationTypes = {
  NORMAL: 0,
  ERROR: 1
}

export const actions = {
  BLOGS_FETCH: 'BLOGS_FETCH',
  BLOG_CREATE: 'BLOG_CREATE',
  BLOG_UPDATE: 'BLOG_UPDATE',
  BLOG_DELETE: 'BLOG_DELETE',
  USERS_FETCH: 'USERS_FETCH',
  AUTH_LOGIN: '  AUTH_LOGIN',
  AUTH_LOGOUT: '  AUTH_LOGOUT',
  NOTIFICATION_SHOW: 'NOTIFICATION_SHOW',
  NOTIFICATION_CLEAR: '  NOTIFICATION_CLEAR'
}